### ISSUE TITLE
gulp / spawn Jekyll error

### ISSUE THREAD

**Issue by jsmith0434** [longpdo/neumorphism#15]
When walking through the installation instructions (https://github.com/jsmith0434/website/blob/master/README.md#getting-started), I followed all the steps through "gulp" with no trouble.  However, when I run the gulp command, I get the following stack trace:

[15:54:10] Using gulpfile ~\website\gulpfile.js
[15:54:10] Starting 'default'...
[15:54:10] Starting 'watchData'...
[15:54:10] Starting 'watchMarkup'...
[15:54:10] Starting 'watchScripts'...
[15:54:10] Starting 'watchStyles'...
[15:54:10] Starting 'styles'...
[15:54:10] Starting 'stylesVendors'...
[15:54:10] Starting 'scripts'...
[15:54:10] Starting 'scriptsVendors'...
[15:54:13] Finished 'scripts' after 3.06 s
[15:54:13] Finished 'styles' after 3.07 s
[15:54:13] Finished 'stylesVendors' after 3.07 s
[15:54:13] Finished 'scriptsVendors' after 3.07 s
[15:54:13] Starting 'jekyll'...
[15:54:13] 'jekyll' errored after 6.7 ms
[15:54:13] Error: spawn bundle ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[15:54:13] 'default' errored after 3.09 s

I've tried troubleshooting and can't figure out how to get past this.  Needless to say, http://localhost:4000/ is a "site can't be reached" page.  I'm a data scientist, not a developer, so I'm new to most of this.

**Comment by manu156** [comment]
I'm not sure but I think this might be a Windows specific error.
similar: 
https://github.com/willianjusten/cards-jekyll-template/issues/20
https://github.com/forestryio/create-static-site/issues/42

**Comment by longpdo** [comment]
Thanks @manu156 for providing a solution, since I could not reproduce the error as a Mac user.
