### ISSUE TITLE
No way to use it on Windows 10 ?

### ISSUE THREAD

**Issue by LaCreArthur** [longpdo/neumorphism#16]
Using Windows 10, I cannot get the page to work.
It's been 5 hours now, managing to slowly advance to your Prerequisites and Installation process, because there were multiples errors and roadblock for each commands. 
I'm finally at the "gulp" command stage and it fails at starting Jekyll, I've added a function to detail the error source : 
```[13:06:50] Starting 'jekyll'...
spawn called
[Arguments] {
  '0': 'bundle',
  '1': [
    'exec',
    'jekyll',
    'build',
    '--incremental',
    '--config=_config.yml,_config_dev.yml'
  ],
  '2': { stdio: 'inherit' }
}
[13:06:50] 'jekyll' errored after 5.21 ms
[13:06:50] Error: spawn bundle ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[13:06:50] 'default' errored after 1.96 s
```
So the error should came from `bundle exec jekyll build --incremental --config=_config.yml,_config_dev.yml` but this command alone works fine, saying 
```Configuration file: _config.yml
Configuration file: _config_dev.yml
            Source: C:/XXX
       Destination: C:/XXX/_site
 Incremental build: enabled
      Generating...
                    done in 0.137 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```
The result page is completely broken, no CSS or JS are working, I'm giving up.
It would be appreciate if you have guidance to help me and if your documentation was clearer ;
There are too many shortcuts in the installation process (ex: suddenly using the gulp cmd, no mention to install it). 
When going for 1.2, and cloning the repo, the point 2. is invalid.
Every command as is, errored on Windows, if it's the case, it should be stated that windows is not supported. 
I'm really sad because I love the design of this template :(

**Comment by longpdo** [comment]
>  I'm really sad because I love the design of this template :(

FIrst, thanks for liking my theme and trying it out.

>  Every command as is, errored on Windows, if it's the case, it should be stated that windows is not supported.

Second, I did mention right under `Getting Started` that my setup commands are MacOS only: `The commands and instructions I provide are for MacOS - please look up the specific commands for your OS on your own.`
Until now, I could only provide commands for MacOS, since I work primarly on a Macbook - I will try to get access to a Windows PC to check the setup process there and maybe update the documentation afterwards.

>  There are too many shortcuts in the installation process (ex: suddenly using the gulp cmd, no mention to install it).

In point 3, I pointed out to use `yarn` - which will install all npm dependencies to your local repository. Gulp is one of the dependencies listed in the package.json - therefore it will be installed.


---

I will try to set it up myself on a Windows PC and update the documentation accordingly - until then I will keep this issue open.
Thanks for your feedback

**Comment by LaCreArthur** [comment]
Thanks for your reply and I understand that you don't had a Windows to make the doc for it. Sorry I wrote the comment right on the spot :s !

**Comment by longpdo** [comment]
Its okay 👍 I know how it is when something does not work. I will try to keep you updated.

**Comment by hamzawinix** [comment]
> Its okay 👍 I know how it is when something does not work. I will try to keep you updated.

you didnt keep us updated :(, great theme btw, still cant run it on windows

**Comment by brycekinsey** [comment]
It's definitely a pain to get working properly on Windows (took me a day of troubleshooting), but I can confirm that it does Work on Windows 10.

**Comment by Cesgilher** [comment]
> It's definitely a pain to get working properly on Windows (took me a day of troubleshooting), but I can confirm that it does Work on Windows 10.

Could you explain the process?? I can't make it work

**Comment by Andrew-J-Larson** [comment]
Have to make sure that https://github.com/moxystudio/node-cross-spawn is installed (maybe just a Windows only issue?), and then replace the following in the `gulpfile.js`:
- `var cp = require('child_process');` into `var cp = require('cross-spawn');`

Afterwards, if you run the `bundle exec jekyll build --incremental --config=_config.yml,_config_dev.yml` command manually, and find `taint` errors, make sure to install Ruby 3.1.x (3.2.x removes support for `taint`) and switch to that version with `ridk use` if you're going to continue using multiple versions of Ruby. Then you might need to rerun `gem install bundler jekyll` and `bundle install`.

Now if you run `gulp`, things should work properly.

**Comment by Andrew-J-Larson** [comment]
Also, not sure if it's just a quirk for me, but changes to `_config.yml` (after the first build) don't seem take affect until updating files in `_includes`.

**Comment by Andrew-J-Larson** [comment]
> > It's definitely a pain to get working properly on Windows (took me a day of troubleshooting), but I can confirm that it does Work on Windows 10.
> 
> Could you explain the process?? I can't make it work

See above, got my website running with the theme now: https://andrew-larson.dev
