### ISSUE TITLE
SCSS doesn't update automatically

### ISSUE THREAD

**Issue by achieveordie** [longpdo/neumorphism#32]
I've been trying to change the looks that neumorphism offers. For that, I've made some changes in `./_sass/main.scss`; but since it doesn't have a front matter, jekyll seems to make no changes. I suppose it needs to be recompiled before changes are reflected but I'm not sure how I'm supposed to go about it.

I've also tried `npx bundle exec gulp` to rebuild contents as per `gulpfile.js` but that gives the following error:
```
$ npx bundle exec gulp
[21:06:51] Using gulpfile D:\Projects\PersonalWebsite\gulpfile.js
[21:06:51] Starting 'default'...
[21:06:51] Starting 'watchData'...
[21:06:51] Starting 'watchMarkup'...
[21:06:51] Starting 'watchScripts'...
[21:06:51] Starting 'watchStyles'...
[21:06:51] Starting 'styles'...
[21:06:51] Starting 'stylesVendors'...
[21:06:51] Starting 'scripts'...
[21:06:51] Starting 'scriptsVendors'...
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
[21:06:54] Finished 'scripts' after 2.95 s
[21:06:54] Finished 'styles' after 2.95 s
[21:06:55] Finished 'stylesVendors' after 3.89 s
[21:06:58] Finished 'scriptsVendors' after 6.75 s
[21:06:58] Starting 'jekyll'...
[21:06:58] 'jekyll' errored after 9.94 ms
[21:06:58] Error: spawn bundle ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[21:06:58] 'default' errored after 6.78 s
[21:06:58] The following tasks did not complete: <parallel>, watchData, watchMarkup, watchScripts, watchStyles
[21:06:58] Did you forget to signal async completion?
```

I'm not familiar with web development so I'm not really sure how to proceed. Any help will be great!

`Windows version: 10`
`Ruby: 2.7.0`
`npx: 6.4.1`
`bundler: 2.1.4`

**Comment by achieveordie** [comment]
smh restarting my pc seemed to work. Closing issue.
